### ISSUE TITLE
Display SSE events calendar on the events page

### ISSUE THREAD

**Issue by stanglersm** [msoe-sse/msoe-sse.github.io#37]
Note from the author: not sure how possible this is, but I thought it would be fun to put in anyway.

Let's see if there's a way to display the SSE events calendar on the [Events](http://msoe-sse.com/events/) page itself without having to go through all of the hassle of adding the calendar to your google calendar and all that.

[Shareable Calendar Link](https://calendar.google.com/calendar/b/4?cid=NTJiMDVjNXVncTExZjMwaDUzZDZ0dXE1ZGNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ)

As a student, I want to see what events SSE is running quickly, so I can see if any of them peak my interest.

In order of how they should be done:
- [x] Get literally anything to show up
- [x] Get content to show up in a month view (see what Google already does for you in terms of displaying stuff if anything)
- [x] Make that calendar not awful to look at or interact with
- [x] Have options for viewing by the week or by the month

**Comment by GFLEMING133** [comment]
This happens to be in our backlog currently, so we'll link this backlog item to the issue here. Question in terms of calendar content though--we were hoping to integrate with the google calendar and have it added as a modal onto one of our pages. Would that be okay? I'm not sure whether or not that would include different views for week/month viewing, but that's definitely something we'll check!

**Comment by stanglersm** [comment]
@GFLEMING133 Whatever works! I was just kind of spitting out ideas - take them all as you will, and do what works best - you know the system!

**Comment by GFLEMING133** [comment]
Hey @stanglersm, would you be able to verify that the current solution matches the issue criterion filed? And would be be able to close this issue?

**Comment by stanglersm** [comment]
Looks great!
