### ISSUE TITLE
msoe-sse website does not use https

### ISSUE THREAD

**Issue by balloneij** [msoe-sse/msoe-sse.github.io#97]
As a Grace I would like to enable https on the msoe-sse website so the website is more secure

**Comment by paulickj** [comment]
The problem seems to be stemming from the SSL certificate.  I have attached the warning from Firefox about the "Bad Certificate." A potential solution to this problem would be changing the nameserver to one that provides SSL certificates like Cloudflare.
![SSL error](https://user-images.githubusercontent.com/55640316/65380367-e025df80-dc9f-11e9-9e24-6459a81470ab.PNG)

**Comment by paulickj** [comment]
Looks like this issue could be attributed to incorrect A records. Found article on GitHub talking about Apex Domains. Looking at other examples the SOA Expire and Refresh Value are out of the recommended range. From the article GitHub wants A records for:
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
with the ttl set to 3600. Hopefully those changes will fix the https issue.

https://docs.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site

**Comment by Sylvyrfysh** [comment]
I'm working on all DNS records, I'll look into this.

**Comment by andy-wojciechowski** [comment]
I will note that I don't have access to update the DNS records for msoe-sse.com. I think you need to get in touch for Cody Haws for that since he's the actual owner of the msoe-sse.com domain. If you need help getting a hold of him for this I should be able to help with that.

**Comment by Sylvyrfysh** [comment]
This (https://coffeegist.com/gist/custom-domains-with-ssl-for-github-pages/) should actually fix this issue. This has nothing to do with the DNS records, but they still need updating.
